/*
 * Copyright (C) 2021 AlenPaulVarghese <alenpaul2001@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.alenpaul2001.coronadashboard;

import Db.Database;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author AlenPaulVarghese <alenpaul2001@gmail.com>
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        // a = new javax.swing.ImageIcon(getClass().getRe);
        System.out.println(System.getProperty("user.dir"));
        initComponents();
    }

    /**
     * Hover animation to change color when mouse entered 
     */
    public static void HoverAnimation(boolean exit, java.awt.event.MouseEvent evt){
        javax.swing.JLabel lbl = (javax.swing.JLabel) evt.getComponent();
        javax.swing.JPanel pnl = (javax.swing.JPanel) lbl.getParent();
        // if else onliner; basically this means if exit is true then use one color else another color
        java.awt.Color color = ((exit == true) ? lbl.getForeground(): new Color(88, 104, 220));
        // https://gist.github.com/TabsPH/4057899
        pnl.setBackground(color);
        pnl.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboard_panel = new javax.swing.JPanel();
        side_panel = new javax.swing.JPanel();
        app_icon_area = new javax.swing.JPanel();
        app_icon = new javax.swing.JLabel();
        dashboard_icon_area = new javax.swing.JPanel();
        dashboard_icon = new javax.swing.JLabel();
        database_icon_area = new javax.swing.JPanel();
        database_icon = new javax.swing.JLabel();
        settings_icon_area = new javax.swing.JPanel();
        settings_icon = new javax.swing.JLabel();
        about_icon_area = new javax.swing.JPanel();
        about_icon = new javax.swing.JLabel();
        recovered_main = new javax.swing.JPanel();
        recovered_text_area = new javax.swing.JPanel();
        recovered_text = new javax.swing.JLabel();
        text_recovered = new javax.swing.JLabel();
        death_main = new javax.swing.JPanel();
        death_text_area = new javax.swing.JPanel();
        death_text = new javax.swing.JLabel();
        text_death = new javax.swing.JLabel();
        confirmed_main = new javax.swing.JPanel();
        confirmed_text_area = new javax.swing.JPanel();
        confirmed_text = new javax.swing.JLabel();
        text_confirmed = new javax.swing.JLabel();
        free_panel = new javax.swing.JPanel();
        information_panel = new javax.swing.JPanel();
        information_text_area = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        dashboard_panel.setPreferredSize(new java.awt.Dimension(940, 500));

        side_panel.setBackground(new java.awt.Color(28, 38, 61));
        side_panel.setPreferredSize(new java.awt.Dimension(100, 500));

        app_icon_area.setBackground(new java.awt.Color(28, 38, 61));
        app_icon_area.setMinimumSize(new java.awt.Dimension(100, 70));
        app_icon_area.setPreferredSize(new java.awt.Dimension(100, 70));

        app_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        app_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/covid-50x50.png"))); // NOI18N
        app_icon.setToolTipText("");
        app_icon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        app_icon.setPreferredSize(new java.awt.Dimension(100, 70));

        javax.swing.GroupLayout app_icon_areaLayout = new javax.swing.GroupLayout(app_icon_area);
        app_icon_area.setLayout(app_icon_areaLayout);
        app_icon_areaLayout.setHorizontalGroup(
            app_icon_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(app_icon_areaLayout.createSequentialGroup()
                .addComponent(app_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        app_icon_areaLayout.setVerticalGroup(
            app_icon_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(app_icon_areaLayout.createSequentialGroup()
                .addComponent(app_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        dashboard_icon_area.setBackground(new java.awt.Color(39, 49, 70));

        dashboard_icon.setForeground(new java.awt.Color(39, 49, 70));
        dashboard_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboard_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-home-24.png"))); // NOI18N
        dashboard_icon.setToolTipText("");
        dashboard_icon.setPreferredSize(new java.awt.Dimension(100, 60));
        dashboard_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboard_iconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboard_iconMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout dashboard_icon_areaLayout = new javax.swing.GroupLayout(dashboard_icon_area);
        dashboard_icon_area.setLayout(dashboard_icon_areaLayout);
        dashboard_icon_areaLayout.setHorizontalGroup(
            dashboard_icon_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboard_icon_areaLayout.createSequentialGroup()
                .addComponent(dashboard_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dashboard_icon_areaLayout.setVerticalGroup(
            dashboard_icon_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboard_icon_areaLayout.createSequentialGroup()
                .addComponent(dashboard_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        database_icon_area.setBackground(new java.awt.Color(28, 38, 61));

        database_icon.setForeground(new java.awt.Color(28, 38, 61));
        database_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        database_icon.setIcon(new javax.swing.ImageIcon("/home/stark/Desktop/creations/piechart-30x30.png")); // NOI18N
        database_icon.setToolTipText("");
        database_icon.setPreferredSize(new java.awt.Dimension(100, 60));
        database_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                database_iconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                database_iconMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout database_icon_areaLayout = new javax.swing.GroupLayout(database_icon_area);
        database_icon_area.setLayout(database_icon_areaLayout);
        database_icon_areaLayout.setHorizontalGroup(
            database_icon_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, database_icon_areaLayout.createSequentialGroup()
                .addComponent(database_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        database_icon_areaLayout.setVerticalGroup(
            database_icon_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(database_icon_areaLayout.createSequentialGroup()
                .addComponent(database_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        settings_icon_area.setBackground(new java.awt.Color(28, 38, 61));
        settings_icon_area.setPreferredSize(new java.awt.Dimension(100, 60));

        settings_icon.setForeground(new java.awt.Color(28, 38, 61));
        settings_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settings_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-settings-24.png"))); // NOI18N
        settings_icon.setToolTipText("");
        settings_icon.setPreferredSize(new java.awt.Dimension(100, 60));
        settings_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settings_iconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settings_iconMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout settings_icon_areaLayout = new javax.swing.GroupLayout(settings_icon_area);
        settings_icon_area.setLayout(settings_icon_areaLayout);
        settings_icon_areaLayout.setHorizontalGroup(
            settings_icon_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settings_icon_areaLayout.createSequentialGroup()
                .addComponent(settings_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        settings_icon_areaLayout.setVerticalGroup(
            settings_icon_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settings_icon_areaLayout.createSequentialGroup()
                .addComponent(settings_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        about_icon_area.setBackground(new java.awt.Color(28, 38, 61));
        about_icon_area.setPreferredSize(new java.awt.Dimension(100, 60));

        about_icon.setForeground(new java.awt.Color(28, 38, 61));
        about_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        about_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/about-icon31.png"))); // NOI18N
        about_icon.setToolTipText("null");
        about_icon.setPreferredSize(new java.awt.Dimension(100, 60));
        about_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                about_iconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                about_iconMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout about_icon_areaLayout = new javax.swing.GroupLayout(about_icon_area);
        about_icon_area.setLayout(about_icon_areaLayout);
        about_icon_areaLayout.setHorizontalGroup(
            about_icon_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, about_icon_areaLayout.createSequentialGroup()
                .addComponent(about_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        about_icon_areaLayout.setVerticalGroup(
            about_icon_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(about_icon_areaLayout.createSequentialGroup()
                .addComponent(about_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout side_panelLayout = new javax.swing.GroupLayout(side_panel);
        side_panel.setLayout(side_panelLayout);
        side_panelLayout.setHorizontalGroup(
            side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(app_icon_area, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashboard_icon_area, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(database_icon_area, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settings_icon_area, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(about_icon_area, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        side_panelLayout.setVerticalGroup(
            side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side_panelLayout.createSequentialGroup()
                .addComponent(app_icon_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashboard_icon_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(database_icon_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settings_icon_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(about_icon_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 166, Short.MAX_VALUE))
        );

        recovered_main.setBackground(new java.awt.Color(198, 246, 213));
        recovered_main.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        recovered_main.setPreferredSize(new java.awt.Dimension(200, 150));
        recovered_main.setLayout(new java.awt.BorderLayout());

        recovered_text_area.setBackground(new java.awt.Color(240, 255, 244));

        recovered_text.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        recovered_text.setForeground(new java.awt.Color(56, 161, 105));
        recovered_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recovered_text.setText("0");
        recovered_text.setToolTipText("");

        javax.swing.GroupLayout recovered_text_areaLayout = new javax.swing.GroupLayout(recovered_text_area);
        recovered_text_area.setLayout(recovered_text_areaLayout);
        recovered_text_areaLayout.setHorizontalGroup(
            recovered_text_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
            .addGroup(recovered_text_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(recovered_text_areaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(recovered_text)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        recovered_text_areaLayout.setVerticalGroup(
            recovered_text_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(recovered_text_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(recovered_text_areaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(recovered_text)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        recovered_main.add(recovered_text_area, java.awt.BorderLayout.PAGE_START);

        text_recovered.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        text_recovered.setForeground(new java.awt.Color(56, 161, 105));
        text_recovered.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_recovered.setText("Recovered");
        recovered_main.add(text_recovered, java.awt.BorderLayout.CENTER);

        death_main.setBackground(new java.awt.Color(226, 232, 240));
        death_main.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        death_main.setPreferredSize(new java.awt.Dimension(200, 150));
        death_main.setLayout(new java.awt.BorderLayout());

        death_text_area.setBackground(new java.awt.Color(237, 242, 247));

        death_text.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        death_text.setForeground(new java.awt.Color(113, 128, 150));
        death_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        death_text.setText("0");
        death_text.setToolTipText("");

        javax.swing.GroupLayout death_text_areaLayout = new javax.swing.GroupLayout(death_text_area);
        death_text_area.setLayout(death_text_areaLayout);
        death_text_areaLayout.setHorizontalGroup(
            death_text_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
            .addGroup(death_text_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(death_text_areaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(death_text)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        death_text_areaLayout.setVerticalGroup(
            death_text_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(death_text_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(death_text_areaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(death_text)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        death_main.add(death_text_area, java.awt.BorderLayout.PAGE_START);

        text_death.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        text_death.setForeground(new java.awt.Color(113, 128, 150));
        text_death.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_death.setText("Deaths");
        death_main.add(text_death, java.awt.BorderLayout.CENTER);

        confirmed_main.setBackground(new java.awt.Color(254, 215, 215));
        confirmed_main.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        confirmed_main.setPreferredSize(new java.awt.Dimension(200, 150));
        confirmed_main.setLayout(new java.awt.BorderLayout());

        confirmed_text_area.setBackground(new java.awt.Color(255, 245, 245));

        confirmed_text.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        confirmed_text.setForeground(new java.awt.Color(229, 62, 62));
        confirmed_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmed_text.setText("0");
        confirmed_text.setToolTipText("");

        javax.swing.GroupLayout confirmed_text_areaLayout = new javax.swing.GroupLayout(confirmed_text_area);
        confirmed_text_area.setLayout(confirmed_text_areaLayout);
        confirmed_text_areaLayout.setHorizontalGroup(
            confirmed_text_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(confirmed_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        );
        confirmed_text_areaLayout.setVerticalGroup(
            confirmed_text_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(confirmed_text, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        confirmed_main.add(confirmed_text_area, java.awt.BorderLayout.PAGE_START);

        text_confirmed.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        text_confirmed.setForeground(new java.awt.Color(229, 62, 62));
        text_confirmed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_confirmed.setText("Confirmed");
        confirmed_main.add(text_confirmed, java.awt.BorderLayout.CENTER);

        free_panel.setPreferredSize(new java.awt.Dimension(840, 280));

        information_panel.setBackground(new java.awt.Color(198, 246, 213));
        information_panel.setPreferredSize(new java.awt.Dimension(840, 40));

        information_text_area.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        information_text_area.setText("loading...");

        javax.swing.GroupLayout information_panelLayout = new javax.swing.GroupLayout(information_panel);
        information_panel.setLayout(information_panelLayout);
        information_panelLayout.setHorizontalGroup(
            information_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(information_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(information_text_area, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
                .addContainerGap())
        );
        information_panelLayout.setVerticalGroup(
            information_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(information_text_area, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout free_panelLayout = new javax.swing.GroupLayout(free_panel);
        free_panel.setLayout(free_panelLayout);
        free_panelLayout.setHorizontalGroup(
            free_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(free_panelLayout.createSequentialGroup()
                .addComponent(information_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        free_panelLayout.setVerticalGroup(
            free_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, free_panelLayout.createSequentialGroup()
                .addGap(0, 240, Short.MAX_VALUE)
                .addComponent(information_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout dashboard_panelLayout = new javax.swing.GroupLayout(dashboard_panel);
        dashboard_panel.setLayout(dashboard_panelLayout);
        dashboard_panelLayout.setHorizontalGroup(
            dashboard_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboard_panelLayout.createSequentialGroup()
                .addComponent(side_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(dashboard_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboard_panelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(confirmed_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(recovered_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(death_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addComponent(free_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        dashboard_panelLayout.setVerticalGroup(
            dashboard_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboard_panelLayout.createSequentialGroup()
                .addGroup(dashboard_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dashboard_panelLayout.createSequentialGroup()
                        .addGroup(dashboard_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmed_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(death_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recovered_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(free_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(side_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(dashboard_panel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Connection db = Database.getConnection();
            ResultSet r = Database.queryCountry(db, "Global");
            r.next();
            confirmed_text.setText(String.valueOf(r.getInt("confirmed")));
            recovered_text.setText(String.valueOf(r.getInt("recovered")));
            death_text.setText(String.valueOf(r.getInt("death")));
            information_panel.setVisible(false);
        } catch (SQLException ex) {
            information_panel.setBackground(new java.awt.Color(254,215,215));
            information_text_area.setText("Could not connect into database");
        } catch (Exception ex){
            information_panel.setBackground(new java.awt.Color(254,215,215));
            information_text_area.setText(ex.getMessage());
        } finally {
            information_panel.repaint();
        }
    }//GEN-LAST:event_formWindowOpened

    private void dashboard_iconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_iconMouseEntered
        HoverAnimation(false, evt);
    }//GEN-LAST:event_dashboard_iconMouseEntered

    private void dashboard_iconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_iconMouseExited
       HoverAnimation(true, evt);
    }//GEN-LAST:event_dashboard_iconMouseExited

    private void database_iconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_database_iconMouseEntered
        HoverAnimation(false, evt);
    }//GEN-LAST:event_database_iconMouseEntered

    private void database_iconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_database_iconMouseExited
        HoverAnimation(true, evt);
    }//GEN-LAST:event_database_iconMouseExited

    private void settings_iconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settings_iconMouseEntered
        HoverAnimation(false, evt);
    }//GEN-LAST:event_settings_iconMouseEntered

    private void settings_iconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settings_iconMouseExited
        HoverAnimation(true, evt);
    }//GEN-LAST:event_settings_iconMouseExited

    private void about_iconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about_iconMouseEntered
        HoverAnimation(false, evt);
    }//GEN-LAST:event_about_iconMouseEntered

    private void about_iconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about_iconMouseExited
        HoverAnimation(true, evt);
    }//GEN-LAST:event_about_iconMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about_icon;
    private javax.swing.JPanel about_icon_area;
    private javax.swing.JLabel app_icon;
    private javax.swing.JPanel app_icon_area;
    private javax.swing.JPanel confirmed_main;
    private javax.swing.JLabel confirmed_text;
    private javax.swing.JPanel confirmed_text_area;
    private javax.swing.JLabel dashboard_icon;
    private javax.swing.JPanel dashboard_icon_area;
    private javax.swing.JPanel dashboard_panel;
    private javax.swing.JLabel database_icon;
    private javax.swing.JPanel database_icon_area;
    private javax.swing.JPanel death_main;
    private javax.swing.JLabel death_text;
    private javax.swing.JPanel death_text_area;
    private javax.swing.JPanel free_panel;
    private javax.swing.JPanel information_panel;
    private javax.swing.JLabel information_text_area;
    private javax.swing.JPanel recovered_main;
    private javax.swing.JLabel recovered_text;
    private javax.swing.JPanel recovered_text_area;
    private javax.swing.JLabel settings_icon;
    private javax.swing.JPanel settings_icon_area;
    private javax.swing.JPanel side_panel;
    private javax.swing.JLabel text_confirmed;
    private javax.swing.JLabel text_death;
    private javax.swing.JLabel text_recovered;
    // End of variables declaration//GEN-END:variables
}
